### PR TITLE
Add initial list of TSC members

### LINKED ISSUE #1: Finalize membership of TSC

### PR DESCRIPTION
**Pull request by planetf1**
This PR adds the initial list of TSC members

Please review and comment if there's any noticeable omissions/suggestions  as per #1 

Fixes #1

### CODE REVIEW

**Review by dstebila — APPROVED** [review]

**Comment by dstebila** [comment]
If we're pulling from the maintainers as listed in https://github.com/pq-code-package/tsc/issues/1#issuecomment-2043237181, what about @jschanck?

**Comment by planetf1** [comment]
@dstebila Agree, I would very much like to add @jschanck.
I hadn't added so far as we need to be confident we can achieve quorum (50%) as per the [charter](https://github.com/pq-code-package/tsc/blob/main/charter/charter-2024-01-29.pdf), so need to ensure the voting members are able to regularly participate. The existing list is based on email or github confirmations.
Would you be able to check if he's interested?.Or perhaps @cryptojedi ?
Whether voting member or not his contributions (and all the others!) have been, and will be, immensely valuable.

I think for now we add, and can change later if needed.. will wait for comments otherwise update tomorrow.

**Review by franziskuskiefer — APPROVED** [review]
Thanks

**Comment by dstebila** [comment]
Can we add Tiago Oliveira from the Formosa Project to the TSC?  The idea here is to have on board both someone who works on libjade implementations (Tiago) and libjade verification (Manuel).

**Review by mkannwischer — APPROVED** [review]

**Comment by planetf1** [comment]
Added @tfaoliveira .

**Pull request merged**
