### PR TITLE
#117 add pravek as tsc voting member

### LINKED ISSUE #117: Add Pravek as TSC member
Pravek Sharma has been voted in as a TSC member on the project

- [x] invite @praveksharma to organization
- [x] add as TSC member in clowarden
- [x] add as member in `members/index.md`

### PR DESCRIPTION
**Pull request by planetf1**
Adds pravek as tsc voting member

Fixes #117

### CODE REVIEW

**Comment by praveksharma** [comment]
@planetf1, #117 says I have been invited to join a organisation but I could not find an invitation going through my email/notificatoins. Is there something I need to do before this PR can go through?

**Comment by planetf1** [comment]
@praveksharma If manual, I'd explicitly invite you. However I don't have full admin, and our access is controlled by CloWarden. Ry advised I just need to add you, which is what this PR does. I just need an approver.

@ryjones are you ok with this change? Can you approve?

**Review by ryjones — APPROVED** [review]

**Comment by praveksharma** [comment]
I recieved an invitation once the changes were approved here. Thank you @planetf1, @ryjones.

**Comment by planetf1** [comment]
@praveksharma merged now too, so you should appear on the list of members and have higher access to the repos.

**Pull request merged**
